### ISSUE TITLE
Link to "CircuitPython Made Easy" doesn't work

### ISSUE THREAD

**Issue by bhrutledge** [adafruit/PyCon2019#12]
Talking to @kattni, it seems that https://adafru.it/cp-made-easy-on-cpx should go to https://learn.adafruit.com/circuitpython-made-easy-on-circuit-playground-express. However, it just goes to https://www.adafruit.com/.

**Comment by tannewt** [comment]
@bhrutledge where is that link? It looks like https://adafru.it/cp-on-cpx-made-easy was set correctly.

**Comment by ptorrone** [comment]
@bhrutledge all fixed, thankya - https://adafru.it/cp-on-cpx-made-easy
